### ISSUE TITLE
win7:无法定位程序输入点GetHostNameW于动态链接库WS2_32.dll上

### ISSUE THREAD

**Issue by m000000n** [rerender2021/language-shadow#1]
![image](https://user-images.githubusercontent.com/19919232/219873595-24a7328b-2a3c-4359-b01b-94ab24945cb3.png)

**Comment by rerender2021** [comment]
# 问题原因

直接原因是内置使用的node版本14.20.0太新了，无法在windows 7上运行

相关资料：

- https://cnodejs.org/topic/61584584fe0c51b4beaeca62
- https://www.cnblogs.com/bdua/p/16472726.html

> 可在win7运行的最低node版本：https://stackoverflow.com/questions/62212754/latest-nodejs-compatible-with-windows-7#:~:text=Support%20for%20Windows%207%20ended%20on%20January%2014%2C%202020..

其它：由于使用了vercel pkg打包，最低支持的系统版本是windows 8.1，所以采取打包的方式，最低也要win 8.1才行

> 最低系统要求：https://www.npmjs.com/package/pkg-fetch

# 解决方式

由于我的开发 & 运行环境是win10，所以暂时无法测试win7上打包运行的场景。但是如果只是运行的话，应该可以采用以下方式绕过：

- 使用低版本node: 14.15.0
- 设置环境变量绕过node环境检查
- 不使用pkg打包，而是直接用绿色版node运行js

可以下载这个压缩包，它里面完成了这些步骤，点击`run.bat`运行：

https://github.com/rerender2021/language-shadow/releases/download/1.0.0/language-shadow-win7.zip

**Comment by rerender2021** [comment]
我装了个win7，试了下还是不行：依赖的一个库缺很多dll

![image](https://user-images.githubusercontent.com/87927336/219951037-6a2fc619-a1bb-40d5-8658-cb2db05aace0.png)

**Comment by m000000n** [comment]
估计是系统的问题，看来必须要升级到win10了
